### ISSUE TITLE
Could I contribute to Sigil?

### ISSUE THREAD

**Issue by jwvdveen** [user-none/Sigil#50]
While exploring the latest source code for Sigil, I found several unused functions and widgets.
For example, in the Table of Contents dock there is an QPushButton which is
not used. I don't know if is it not used anymore or if it is put there for
future plans.

Another example, again in the Table of contents, would be the ExpandAll and the CollapseAll functions which could be connected directly to the treeview.

Perhaps I could be of some service by cleaning up obsolete functions and
widgets so you and your team can focus on forward development?

**Comment by kevinhendricks** [comment]
Hi,
Good contributions are always welcome!  Simply fork this repository and send pull requests for **small** groups of related changes so that we can see they are obviously correct and revert them easily  if they end up breaking anything.

And yes the code does have a number of leftovers given all of the changes, so a systematic clean-up of Sigil code would certainly not hurt.  But be aware that entire modules are being removed and changed in a new trunk version coming up.

Take care,

KevinH

**Comment by jwvdveen** [comment]
Hi, 

Thanks. I will keep an eye on the changes.

Just a question since it is the first time I work with somting like Git.
I've forked Sigil and used QtCreator with git to fetch the stuff to my laptop. And through QtCreator I committed two files, but I can't seem to see the changes uploaded to my fork on github. 
It is probably something simple, but I can't seem to figure it out.

Could you help me?

Jan-Willem

**Comment by jwvdveen** [comment]
Ah, I believe I just figured it out.
My first pull requests should have been added.

**Comment by user-none** [comment]
Closing this out since you know how to contribute and your contribution was accepted.

**Comment by jwvdveen** [comment]
Thanks.
This week I was very bussy, but I hope to continue shortly.

Sincerely,
Jan-Willem van der Veen

Verzonden met mijn Windows Phone
________________________________
Van: John Schember<mailto:notifications@github.com>
Verzonden: ‎31-‎1-‎2015 14:58
Aan: user-none/Sigil<mailto:Sigil@noreply.github.com>
CC: jwvdveen<mailto:jwvdveen@outlook.com>
Onderwerp: Re: [Sigil] Could I contribute to Sigil? (#50)

Closing this out since you know how to contribute and your contribution was accepted.

---
