### ISSUE TITLE
SHA256 checksums wrong?

### ISSUE THREAD

**Issue by PupeMeziwo** [user-none/Sigil#52]
The SHA256 file also contains the checksum of the SHA256 file itself, but this must be wrong.
Please double check if the SHA256 file should also be inserted, as inserting it's own checksum alters it's checksum again... :-)

**Comment by user-none** [comment]
You are correct the checksum file itself should not be included in the file. For some reason when I generate it it's getting in there. Most likely because I'm using `shasum 256 * > sums`. It's creating the file summing it wrong, then writing the sum to the file then doing the other files. I noticed it's first in the file so it's getting read before anything else. I'll add to the release docs to remove that line in the future.

Unfortunately, I'm unwilling to change existing releases.
