### ISSUE TITLE
Sigil displays wrong HTML

### ISSUE THREAD

**Issue by tofi86** [user-none/Sigil#77]
Alright, this is the setting: One of my customers had a problem where Kindle Previewer would issue a warning like this:

```
Warnung(inputpreprocessor):W29008: Tag wegen unsachgemäßer Nutzung abgelehnt: </image>
      In Datei: /var/folders/bm/zcs3s36j3f192rrtdnwf4z1c0000gn/T/mobi-tjFjOP/OEBPS/Text/CoverImage.xhtml     Zeile: 0000015
```

Which translates to `Rejected because of improper use of tag: </image>`

They did a lot of research as they couldn't find such an ending tag in the `CoverImage.xhtml` file. This is how it looked, when they opened the file in Sigil 0.8.6:

![bildschirmfoto 2015-05-29 um 14 29 09](https://cloud.githubusercontent.com/assets/365118/7882566/201e985a-060f-11e5-87e9-dbe014d9121e.png)

They thought it looks right and closed the file again. Still, the epub caused a warning in Kindle Previewer.

They sent it to me for review and I opened the cover file in oXygen Editor – and hey, it looked quite different!

![bildschirmfoto 2015-05-29 um 14 16 00](https://cloud.githubusercontent.com/assets/365118/7882586/50dcd7d6-060f-11e5-90c0-a9b5dc7d02f5.png)

Sigil apparently doesn't display the HTML like it's saved in the EPUB! This is ridiculous!
Please fix this issue!

**Comment by kevinhendricks** [comment]
Thiere was a bug in much older versions of Sigil in that Tidy (used by Sigil) did not know image was a void tag.  This should be fixed in Sigil 0.8.6.  In fact, Sigil 0.8.6 will in fact fix improper non-void image tags upon cleaning if the user enables it in their preferences.

But please understand that like any xml aware parser, Oxygen has its own internal  parser and unless you have loaded the dtd for svg it will parse it as pure xml meaning attributes will change order and non-void tags like image will not be correct. This is true of all xml editors including oxygen.  Order of attributes is not meaningful in xml.

 To verify this is indeed a Sigil issue  please do exactly the following:

1. In Sigil 0.8.6, open that epub and go to cover page in CodeView and verify that the image tag is shown as a void tag (self-closing) and if not fix it.
2. save it to a *new* epub.  Don't just use the old epub as Sigil may have auto-fixed the bad image tag when loaded if the user preferences are set to clean upon load or if the file fails to be well-formed xhtml, so saving it is important here otherwise you are just keeping the original bad text in the file.  Sigil needs to do this to allow WYSIWYG editing in BookView mode.  All files being edited by Sigil must be well-formed at all times to allow BookView editing.
3. unzip the resulting epub and find that cover image xhtml file 
4. With a ****non-xml**** aware text editor, open that file to see if image is written to the file as a void tag or not.  

If not, post a link to that exact file unprocessed by any other software, and to the exact epub being converted by KindlePreviewer here and I will try to track down what is messed up.

**Comment by kevinhendricks** [comment]
FWIW, my guess is you have set Sigil to clean upon load in your Sigil user preferences, and so you see the fixed file in CodeView but never save it.  This is all explained in the Sigil documentation and users of Sigil understand how Sigil works to allow both CodeView and BookView editing simulataneously.  

Simply unzipping the epub and running grep or using a pure text editor would have been the best way to find mark-up anomolies.

**Comment by user-none** [comment]
XHTML allows end tags for ANY element. Sigil is an EPUB application and creates EPUBs. Kindle Previewer auto converts EPUBs and if it can't handle XHTML then this is an issue with Kindle Previewer.

Finally as stated Sigil by default cleans the markup in the EPUB. If you don't save then the changes won't be saved.
